version: "3"
services:
  pg:
    image: postgis-debian
    container_name: 'pg-proxy'
    networks:
      - nearby-network
  gallery-mongo:
    image: mongo:3.6
    container_name: 'gallery-mongo'
    networks:
      - nearby-network
  nearby:
    image: nearby
    container_name: 'nearby-proxy'
    depends_on:
      - pg
    networks:
      - nearby-network
    environment:
      PG_HOST: 'pg'
      PG_USER: 'postgres'
  gallery:
    image: mermanly/gallery
    container_name: 'gallery-proxy'
    depends_on: 
      - gallery-mongo
    networks:
      - nearby-network
    environment:
      DATABASE_HOST: 'gallery-mongo'
  nginx:
    image: js-nginx
    container_name: 'proxy'
    ports:
      - "80:8888"
    depends_on:
      - nearby
      - pg
      - node-proxy
      - gallery
    networks:
      - nearby-network
  node-proxy:
    image: node-proxy
    container_name: 'node-proxy'
    networks:
      - nearby-network
networks:
  nearby-network:
    driver: bridge